---
layout: cv
title: Resume
---
# Ethan M. Abbott


Mobile: 719-985-7588  
Email: ethan.abbott10@outlook.com  


## SUMMARY
Graduated from Liberty High School with a 4.1 GPA. Earned three academic letters and two activity letters. Participated in both high school and club soccer teams, learning the importance of teamwork and how to find your role. Currently developing strength in Python, R, SQL, and Tableau. Comfortable with Microsoft Office products.

Played trumpet and selected for four All-State groups, learning how opportunities stem from hard work. Participated in National Honor Society, providing service to my community. Earned the rank of Eagle Scout with the Boy Scouts of America. Fluent in Spanish.

## WORK HISTORY
### ***Delivery Driver – Steve’s Paint Supply***
**Aug 2024 – Jan 2025**  
Colorado Springs, CO  
- Ensured that material was transported to clients safely in a timely manner.
- Familiarized himself with various storage units for efficient storage and retrieval of material.
- Entrusted with company funds to realize business purchases around town.

### ***Missionary – Church of Jesus Christ of Latter-Day Saints***
**April 2022 – April 2024**  
Mexico, Mexico City West Mission  
- Performed ministering, proselyting, public relations, and service work on a regional level.
- Found and submitted housing solutions for the needs of 135 missionaries including proposals and contract negotiations through church legal department.
- As Executive Secretary for Mission President handled logistics support for materials, equipment and mission resources, including planning transportation for missionaries within the mission or returning home.
- Prepared Residency application (Visa) packages for foreign-serving missionaries and maintained consulate appointment schedules.
- Supported technology maintenance, repair, and training needs.
- Commended for developing and maintaining a culture of obedience and reliability in the aforementioned tasks.

### ***Hotel Maintenance Staff – Hampton Inn and Suites***
**June 2020 – Dec 2022**  
Colorado Springs, CO  
- Successfully serviced and supported hotel amenities and building assets for the #1 rated Hampton Inn & Suites in Colorado.
- Specialized in pool maintenance, grounds keeping, facilities appearance, structural and landscaping improvements to maintain a fully operational, clean hotel property at one of the highest volume per unit hotels in Colorado.

## EDUCATION
**Brigham Young University–Idaho**  
Bachelor of Science—Data Science (anticipated completion July 2026)